### ISSUE TITLE
GLIBC error on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by zocker-160** [ruanformigoni/arts#2]
When trying to execute any command using the offered .arts files, I am getting this error on Ubuntu 22.04:

```
$ ./focal.arts 
./focal.arts: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./focal.arts)
./focal.arts: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./focal.arts)
```

my installed glibc is:
```
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Any idea what is going on?

**Comment by zocker-160** [comment]
oh I am so stupid, I did not notice that I am inside the container lol lmao.

I did expect the bash promt to change, sorry this is 100% my own epic fail.

**Comment by ruanformigoni** [comment]
Hi @zocker-160 , no problem! This software is still in early development, any issues you encounter I'm here.
