### ISSUE TITLE
[Feature Request] ability to mount image and browse it using a file manager

### ISSUE THREAD

**Issue by zocker-160** [ruanformigoni/arts#4]
AFAIK ARTS already works by mounting to `/tmp/.mountXYZ` and then executing whatever is specified. 

Currently however it is not very convenient to edit files which are inside that image as everything needs to be done using the command line. 

Would it be possible to add the ability to just mount the image and then opening the mount path with the default file manager so that one could use that to copy / move / modify files?

I think that could be a very big QOL improvement.

PS: something like `arts-mount` would do and then open the directory using `xdg-open /path/to/mounted/image`
PPS: what exactly is the difference between `arts-exec` and `arts-root` ?

**Comment by ruanformigoni** [comment]
Hi @zocker-160 thanks for the suggestion, I'm working on this and will let you know right after it is finished :)

**Comment by ruanformigoni** [comment]
Hi! Feature implemented in the latest release, instructions in the README.md.

**Comment by zocker-160** [comment]
awesome thank you! :heart:
